/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as PlayTokenRouteImport } from './routes/play.$token'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeagueIdRouteImport } from './routes/_authenticated/league.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTokenRoute = PlayTokenRouteImport.update({
  id: '/play/$token',
  path: '/play/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueIdRoute = AuthenticatedLeagueIdRouteImport.update({
  id: '/league/$id',
  path: '/league/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/play/$token': typeof PlayTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/league/$id': typeof AuthenticatedLeagueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/play/$token': typeof PlayTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/league/$id': typeof AuthenticatedLeagueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/play/$token': typeof PlayTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/_authenticated/league/$id': typeof AuthenticatedLeagueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/owner/login'
    | '/play/$token'
    | '/t/$slug'
    | '/league/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/owner/login'
    | '/play/$token'
    | '/t/$slug'
    | '/league/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/owner/login'
    | '/play/$token'
    | '/t/$slug'
    | '/_authenticated/league/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  PlayTokenRoute: typeof PlayTokenRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$token': {
      id: '/play/$token'
      path: '/play/$token'
      fullPath: '/play/$token'
      preLoaderRoute: typeof PlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$id': {
      id: '/_authenticated/league/$id'
      path: '/league/$id'
      fullPath: '/league/$id'
      preLoaderRoute: typeof AuthenticatedLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeagueIdRoute: typeof AuthenticatedLeagueIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeagueIdRoute: AuthenticatedLeagueIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  PlayTokenRoute: PlayTokenRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
