/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminTournamentIdRouteImport } from './routes/admin.tournament.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/admin/themes',
  path: '/admin/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentIdRoute = AdminTournamentIdRouteImport.update({
  id: '/admin/tournament/$id',
  path: '/admin/tournament/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tournament/$id': typeof AdminTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tournament/$id': typeof AdminTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tournament/$id': typeof AdminTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/themes' | '/admin/' | '/admin/tournament/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/themes' | '/admin' | '/admin/tournament/$id'
  id: '__root__' | '/' | '/admin/themes' | '/admin/' | '/admin/tournament/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTournamentIdRoute: typeof AdminTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/admin/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournament/$id': {
      id: '/admin/tournament/$id'
      path: '/admin/tournament/$id'
      fullPath: '/admin/tournament/$id'
      preLoaderRoute: typeof AdminTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTournamentIdRoute: AdminTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
